# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/examples/traffic-control
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-traffic-control "ns3-dev-traffic-control-debug")
set_tests_properties(ctest-traffic-control PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;1;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-queue-discs-benchmark "ns3-dev-queue-discs-benchmark-debug")
set_tests_properties(ctest-queue-discs-benchmark PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;12;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-fengadaptive "ns3-dev-red-vs-fengadaptive-debug")
set_tests_properties(ctest-red-vs-fengadaptive PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;24;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-nlred "ns3-dev-red-vs-nlred-debug")
set_tests_properties(ctest-red-vs-nlred PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;35;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-tbf-example "ns3-dev-tbf-example-debug")
set_tests_properties(ctest-tbf-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;46;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-cobalt-vs-codel "ns3-dev-cobalt-vs-codel-debug")
set_tests_properties(ctest-cobalt-vs-codel PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;56;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/traffic-control/CMakeLists.txt;0;")
