# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3-dev-time-probe-example-debug")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;1;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3-dev-gnuplot-example-debug")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3-dev-double-probe-example-debug")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3-dev-gnuplot-aggregator-example-debug")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3-dev-gnuplot-helper-example-debug")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3-dev-file-aggregator-example-debug")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3-dev-file-helper-example-debug")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/stats/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/stats/examples/CMakeLists.txt;0;")
