# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/src/network/examples
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3-dev-bit-serializer-debug")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3-dev-main-packet-header-debug")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3-dev-main-packet-tag-debug")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3-dev-packet-socket-apps-debug")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisons "ns3-dev-lollipop-comparisons-debug")
set_tests_properties(ctest-lollipop-comparisons PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/network/examples/CMakeLists.txt;0;")
