# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/src/tap-bridge/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tap-csma "ns3-dev-tap-csma-debug")
set_tests_properties(ctest-tap-csma PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples/CMakeLists.txt;2;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-csma-virtual-machine "ns3-dev-tap-csma-virtual-machine-debug")
set_tests_properties(ctest-tap-csma-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples/CMakeLists.txt;12;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-virtual-machine "ns3-dev-tap-wifi-virtual-machine-debug")
set_tests_properties(ctest-tap-wifi-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples/CMakeLists.txt;21;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-dumbbell "ns3-dev-tap-wifi-dumbbell-debug")
set_tests_properties(ctest-tap-wifi-dumbbell PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples/CMakeLists.txt;32;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/tap-bridge/examples/CMakeLists.txt;0;")
