# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/src/energy/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-generic-battery-discharge-example "ns3-dev-generic-battery-discharge-example-debug")
set_tests_properties(ctest-generic-battery-discharge-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;1;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-generic-battery-wifiradio-example "ns3-dev-generic-battery-wifiradio-example-debug")
set_tests_properties(ctest-generic-battery-wifiradio-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples//" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;8;build_example;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-li-ion-energy-source-example "ns3-dev-li-ion-energy-source-example-debug")
set_tests_properties(ctest-li-ion-energy-source-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;20;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-rv-battery-model-test "ns3-dev-rv-battery-model-test-debug")
set_tests_properties(ctest-rv-battery-model-test PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;27;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-basic-energy-model-test "ns3-dev-basic-energy-model-test-debug")
set_tests_properties(ctest-basic-energy-model-test PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;36;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/energy/examples/CMakeLists.txt;0;")
