# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/src/sixlowpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-example-sixlowpan "ns3-dev-example-sixlowpan-debug")
set_tests_properties(ctest-example-sixlowpan PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples/CMakeLists.txt;1;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan "ns3-dev-example-ping-lr-wpan-debug")
set_tests_properties(ctest-example-ping-lr-wpan PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples/CMakeLists.txt;12;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-beacon "ns3-dev-example-ping-lr-wpan-beacon-debug")
set_tests_properties(ctest-example-ping-lr-wpan-beacon PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples/CMakeLists.txt;23;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-mesh-under "ns3-dev-example-ping-lr-wpan-mesh-under-debug")
set_tests_properties(ctest-example-ping-lr-wpan-mesh-under PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples/CMakeLists.txt;34;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/sixlowpan/examples/CMakeLists.txt;0;")
