# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/scratch
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_lorawan-network-mClass-sim-att "ns3-dev-lorawan-network-mClass-sim-att-debug")
set_tests_properties(ctest-scratch_lorawan-network-mClass-sim-att PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/scratch/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;57;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;69;create_scratch;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_lorawan-network-mClass-sim "ns3-dev-lorawan-network-mClass-sim-debug")
set_tests_properties(ctest-scratch_lorawan-network-mClass-sim PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/scratch/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;57;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;69;create_scratch;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_lorawan-network-sim-att "ns3-dev-lorawan-network-sim-att-debug")
set_tests_properties(ctest-scratch_lorawan-network-sim-att PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/scratch/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;57;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;69;create_scratch;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_lorawan-network-sim "ns3-dev-lorawan-network-sim-debug")
set_tests_properties(ctest-scratch_lorawan-network-sim PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/scratch/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;57;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;69;create_scratch;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3-dev-scratch-simulator-debug")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/scratch/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;57;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;69;create_scratch;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_simple-network-example "ns3-dev-simple-network-example-debug")
set_tests_properties(ctest-scratch_simple-network-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/scratch/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;57;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;69;create_scratch;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_teste "ns3-dev-teste-debug")
set_tests_properties(ctest-scratch_teste PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/scratch/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;57;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;69;create_scratch;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3-dev-scratch-subdir-debug")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;57;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;99;create_scratch;/home/imario/Documentos/UFC/TCC/ns-3/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
