# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/src/mobility/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bonnmotion-ns2-example "ns3-dev-bonnmotion-ns2-example-debug")
set_tests_properties(ctest-bonnmotion-ns2-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-topology "ns3-dev-main-random-topology-debug")
set_tests_properties(ctest-main-random-topology PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-walk "ns3-dev-main-random-walk-debug")
set_tests_properties(ctest-main-random-walk PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-ns2-mobility-trace "ns3-dev-ns2-mobility-trace-debug")
set_tests_properties(ctest-ns2-mobility-trace PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-grid-topology "ns3-dev-main-grid-topology-debug")
set_tests_properties(ctest-main-grid-topology PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;19;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-mobility-trace-example "ns3-dev-mobility-trace-example-debug")
set_tests_properties(ctest-mobility-trace-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;28;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-reference-point-group-mobility-example "ns3-dev-reference-point-group-mobility-example-debug")
set_tests_properties(ctest-reference-point-group-mobility-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;37;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/mobility/examples/CMakeLists.txt;0;")
