# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/src/netanim/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dumbbell-animation "ns3-dev-dumbbell-animation-debug")
set_tests_properties(ctest-dumbbell-animation PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-grid-animation "ns3-dev-grid-animation-debug")
set_tests_properties(ctest-grid-animation PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-star-animation "ns3-dev-star-animation-debug")
set_tests_properties(ctest-star-animation PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-colors-link-description "ns3-dev-colors-link-description-debug")
set_tests_properties(ctest-colors-link-description PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-resources-counters "ns3-dev-resources-counters-debug")
set_tests_properties(ctest-resources-counters PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-wireless-animation "ns3-dev-wireless-animation-debug")
set_tests_properties(ctest-wireless-animation PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;23;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-uan-animation "ns3-dev-uan-animation-debug")
set_tests_properties(ctest-uan-animation PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;36;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/netanim/examples/CMakeLists.txt;0;")
