# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/examples/tcp
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/examples/tcp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tcp-large-transfer "ns3-dev-tcp-large-transfer-debug")
set_tests_properties(ctest-tcp-large-transfer PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;1;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-star-server "ns3-dev-tcp-star-server-debug")
set_tests_properties(ctest-tcp-star-server PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;10;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-star "ns3-dev-star-debug")
set_tests_properties(ctest-star PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;19;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bbr-example "ns3-dev-tcp-bbr-example-debug")
set_tests_properties(ctest-tcp-bbr-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;30;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bulk-send "ns3-dev-tcp-bulk-send-debug")
set_tests_properties(ctest-tcp-bulk-send PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;43;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pcap-nanosec-example "ns3-dev-tcp-pcap-nanosec-example-debug")
set_tests_properties(ctest-tcp-pcap-nanosec-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;52;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-variants-comparison "ns3-dev-tcp-variants-comparison-debug")
set_tests_properties(ctest-tcp-variants-comparison PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;61;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pacing "ns3-dev-tcp-pacing-debug")
set_tests_properties(ctest-tcp-pacing PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;71;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-linux-reno "ns3-dev-tcp-linux-reno-debug")
set_tests_properties(ctest-tcp-linux-reno PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;81;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-validation "ns3-dev-tcp-validation-debug")
set_tests_properties(ctest-tcp-validation PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;92;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-dctcp-example "ns3-dev-dctcp-example-debug")
set_tests_properties(ctest-dctcp-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/tcp/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;104;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/tcp/CMakeLists.txt;0;")
