# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/examples/ipv6
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-fragmentation-ipv6 "ns3-dev-fragmentation-ipv6-debug")
set_tests_properties(ctest-fragmentation-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;1;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-fragmentation-ipv6-two-MTU "ns3-dev-fragmentation-ipv6-two-MTU-debug")
set_tests_properties(ctest-fragmentation-ipv6-two-MTU PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;10;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-icmpv6-redirect "ns3-dev-icmpv6-redirect-debug")
set_tests_properties(ctest-icmpv6-redirect PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;19;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-loose-routing-ipv6 "ns3-dev-loose-routing-ipv6-debug")
set_tests_properties(ctest-loose-routing-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;28;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-ping6-example "ns3-dev-ping6-example-debug")
set_tests_properties(ctest-ping6-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;37;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-radvd-one-prefix "ns3-dev-radvd-one-prefix-debug")
set_tests_properties(ctest-radvd-one-prefix PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;46;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-radvd-two-prefix "ns3-dev-radvd-two-prefix-debug")
set_tests_properties(ctest-radvd-two-prefix PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;55;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-test-ipv6 "ns3-dev-test-ipv6-debug")
set_tests_properties(ctest-test-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;64;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-wsn-ping6 "ns3-dev-wsn-ping6-debug")
set_tests_properties(ctest-wsn-ping6 PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;71;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-fragmentation-ipv6-PMTU "ns3-dev-fragmentation-ipv6-PMTU-debug")
set_tests_properties(ctest-fragmentation-ipv6-PMTU PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/ipv6/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;82;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/ipv6/CMakeLists.txt;0;")
