# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/src/lorawan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-simple-network-example "ns3-dev-simple-network-example-debug")
set_tests_properties(ctest-simple-network-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;1;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-network-server-example "ns3-dev-network-server-example-debug")
set_tests_properties(ctest-network-server-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;8;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-complete-network-example "ns3-dev-complete-network-example-debug")
set_tests_properties(ctest-complete-network-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-adr-example "ns3-dev-adr-example-debug")
set_tests_properties(ctest-adr-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;24;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-lorawan-energy-model-example "ns3-dev-lorawan-energy-model-example-debug")
set_tests_properties(ctest-lorawan-energy-model-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;32;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-aloha-throughput "ns3-dev-aloha-throughput-debug")
set_tests_properties(ctest-aloha-throughput PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;40;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-parallel-reception-example "ns3-dev-parallel-reception-example-debug")
set_tests_properties(ctest-parallel-reception-example PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;48;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-frame-counter-update "ns3-dev-frame-counter-update-debug")
set_tests_properties(ctest-frame-counter-update PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;56;build_lib_example;/home/imario/Documentos/UFC/TCC/ns-3/src/lorawan/examples/CMakeLists.txt;0;")
