# CMake generated Testfile for 
# Source directory: /home/imario/Documentos/UFC/TCC/ns-3/examples/routing
# Build directory: /home/imario/Documentos/UFC/TCC/ns-3/cmake-cache/examples/routing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dynamic-global-routing "ns3-dev-dynamic-global-routing-debug")
set_tests_properties(ctest-dynamic-global-routing PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;1;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-static-routing-slash32 "ns3-dev-static-routing-slash32-debug")
set_tests_properties(ctest-static-routing-slash32 PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;11;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-routing-slash32 "ns3-dev-global-routing-slash32-debug")
set_tests_properties(ctest-global-routing-slash32 PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;21;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-injection-slash32 "ns3-dev-global-injection-slash32-debug")
set_tests_properties(ctest-global-injection-slash32 PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;31;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-global-routing "ns3-dev-simple-global-routing-debug")
set_tests_properties(ctest-simple-global-routing PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;41;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-alternate-routing "ns3-dev-simple-alternate-routing-debug")
set_tests_properties(ctest-simple-alternate-routing PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;51;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-mixed-global-routing "ns3-dev-mixed-global-routing-debug")
set_tests_properties(ctest-mixed-global-routing PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;60;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-routing-ping6 "ns3-dev-simple-routing-ping6-debug")
set_tests_properties(ctest-simple-routing-ping6 PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;70;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-manet-routing-compare "ns3-dev-manet-routing-compare-debug")
set_tests_properties(ctest-manet-routing-compare PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;79;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-ripng-simple-network "ns3-dev-ripng-simple-network-debug")
set_tests_properties(ctest-ripng-simple-network PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;93;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-rip-simple-network "ns3-dev-rip-simple-network-debug")
set_tests_properties(ctest-rip-simple-network PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;102;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-routing-multi-switch-plus-router "ns3-dev-global-routing-multi-switch-plus-router-debug")
set_tests_properties(ctest-global-routing-multi-switch-plus-router PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;111;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-multicast-flooding "ns3-dev-simple-multicast-flooding-debug")
set_tests_properties(ctest-simple-multicast-flooding PROPERTIES  WORKING_DIRECTORY "/home/imario/Documentos/UFC/TCC/ns-3/build/examples/routing/" _BACKTRACE_TRIPLES "/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1630;add_test;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1705;set_runtime_outputdirectory;/home/imario/Documentos/UFC/TCC/ns-3/build-support/macros-and-definitions.cmake;1858;build_exec;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;126;build_example;/home/imario/Documentos/UFC/TCC/ns-3/examples/routing/CMakeLists.txt;0;")
